In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import datetime as dt
from datetime import datetime as dtdt
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import ticker
import matplotlib.dates as mdates
from matplotlib.dates import date2num
from matplotlib.dates import DateFormatter
import seaborn as sns
sns.set()

In [2]:
path = "/Users/iomacbookair2/Documents/lab/DEIM2023/tweet_csv/nichiten/230115_nichiten.csv"
df = pd.read_csv((path))
df['created_at'] = pd.to_datetime(df['created_at'])
df.sort_values(by = 'created_at', ascending = True, inplace = True)
df = df.reset_index(drop=True)
df

,created_at,tweet_id,text,author_id,username,like_count,retweet_count
0,2023-01-15 10:00:00,1614427145639428096,#nichiten おはようございます📻,863003082954645504,miiyan1182,16,0
1,2023-01-15 10:00:01,1614427149708021766,安住さん、中澤さん、スタッフのみなさん、おはようございます。 そして、安住さんおかえりなさい...,309615176,_nohohon_,3,0
2,2023-01-15 10:00:01,1614427149309743105,#nichiten,1225028536181768192,kirienogiraji,0,0
3,2023-01-15 10:00:01,1614427147912847361,#nichiten #安住紳一郎 さぁ！ ”nichiten安住”の2023年 始まりで...,1604297030439825409,start20221218,2,0
4,2023-01-15 10:00:01,1614427148093386752,【局長待遇大復活祭】おはようございます。 #nichiten,134428996,ko_shi_hi_ka_ri,3,0
...,...,...,...,...,...,...,...
3934,2023-01-15 11:59:10,1614457133365592064,エンディングは 「show me」 コロナに罹った安住さんが コロナをないがしろにする 政府...,110780230,kogahi,0,0
3935,2023-01-15 11:59:13,1614457147601088513,安住さん🥸中澤さん👸 高橋洋子さん👸 今日も楽しい2時間でした！ 安住さん🥸、 お身体をお大...,253432251,chico_080909,7,0
3936,2023-01-15 11:59:33,1614457229981417473,中尾明慶さん、好きな俳優さん😆#nichiten,1103562040705077248,mattu_purple,0,0
3937,2023-01-15 11:59:44,1614457276047446027,黒木華ちゃんの『凪のお暇』も『重版出来！』も良かったなぁ。 #nichiten,1409657094,torotaku7,1,0
3938,2023-01-15 11:59:54,1614457317944332294,これが選曲の切り札か。 もう離さへんのや～なのね(笑) #nichiten,618084430,cominglisten,0,0

In [3]:
c_df = df.set_index('created_at').resample('T').count()
like_count_per_minute = df.set_index('created_at')['like_count'].resample('T').sum()
cnt = pd.DataFrame(
    {'created_at' : c_df.index.strftime('%Y-%m-%d %H:%M:%S'), 'tweet' : c_df['text'].values, 'like':like_count_per_minute.values})
cnt

              created_at  tweet  like
0    2023-01-15 10:00:00     60   100
1    2023-01-15 10:01:00     94   147
2    2023-01-15 10:02:00    111    80
3    2023-01-15 10:03:00    105   107
4    2023-01-15 10:04:00     98    61
..                   ...    ...   ...
115  2023-01-15 11:55:00     56    85
116  2023-01-15 11:56:00     55    72
117  2023-01-15 11:57:00     25    53
118  2023-01-15 11:58:00     16    59
119  2023-01-15 11:59:00      7    17

[120 rows x 3 columns]

In [4]:
filename =  "220115_count.csv"
cnt.to_csv(filename, encoding = 'utf-8-sig')