In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import datetime as dt
from datetime import datetime as dtdt
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import ticker
import matplotlib.dates as mdates
from matplotlib.dates import date2num
from matplotlib.dates import DateFormatter
import seaborn as sns
sns.set()

In [2]:
path = "/Users/iomacbookair2/Documents/lab/DEIM2023/tweet_csv/tama/220119_tama.csv"
df = pd.read_csv((path))
df['created_at'] = pd.to_datetime(df['created_at'])
df.sort_values(by = 'created_at', ascending = True, inplace = True)
df = df.reset_index(drop=True)
df

,created_at,text,author_id,username,like_count,retweet_count
0,2022-01-19 13:00:00,#tama954🟢(水曜),863003082954645504,miiyan1182,2,0
1,2022-01-19 13:00:03,突然小声になるツインタワーの片側の人ｗ #tama954,124805427,daradara3,2,0
2,2022-01-19 13:00:28,先週のクロストークで『生活は踊る』から好きな鍋は？ 赤江さん「豆乳鍋」 大吉先生「モツ鍋」 ...,1898062195,otonosuzu,0,0
3,2022-01-19 13:00:30,#tama954,3632462718,suusanja,2,0
4,2022-01-19 13:00:51,愛が一番アイフル～♪からの #博多大吉 先生と赤江工場長による 水曜 #たまむすび 始まった...,293331177,otsukareiwa,0,0
...,...,...,...,...,...,...
1246,2022-01-19 15:31:19,水曜のラストはもやもやする内容のメールが読まれる傾向 こないだのマット？タオル？使わないおじ...,3262736684,kawasister,1,0
1247,2022-01-19 15:31:20,赤江さん、大吉先生、おつかれさまでしたー #tama954,899647676043583490,nakakyou3,0,0
1248,2022-01-19 15:33:38,メールの記録見たけど ないな 思い違いか #tama954,203359937,NRT0,0,0
1249,2022-01-19 15:33:51,昔の思い出はしょうがないでしょ、話しちゃったのはアレだけど。#tama954,1103562040705077248,mattu_purple,0,0
1250,2022-01-19 15:34:20,@Noiseless_Noisy 確か太閤園さんが、閉館されましたのでそれと同時に改装期間に...,309615176,_nohohon_,1,0

In [3]:
c_df = df.set_index('created_at').resample('T').count()
like_count_per_minute = df.set_index('created_at')['like_count'].resample('T').sum()
cnt = pd.DataFrame(
    {'created_at' : c_df.index.strftime('%Y-%m-%d %H:%M:%S'), 'tweet' : c_df['text'].values, 'like':like_count_per_minute.values})
cnt

              created_at  tweet  like
0    2022-01-19 13:00:00      5     6
1    2022-01-19 13:01:00      6     4
2    2022-01-19 13:02:00      6     4
3    2022-01-19 13:03:00     10    45
4    2022-01-19 13:04:00     10     7
..                   ...    ...   ...
150  2022-01-19 15:30:00      4     1
151  2022-01-19 15:31:00      3     3
152  2022-01-19 15:32:00      0     0
153  2022-01-19 15:33:00      2     0
154  2022-01-19 15:34:00      1     1

[155 rows x 3 columns]

In [4]:
filename =  "count.csv"
cnt.to_csv(filename, encoding = 'utf-8-sig')