In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import datetime as dt
from datetime import datetime as dtdt
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import ticker
import matplotlib.dates as mdates
from matplotlib.dates import date2num
from matplotlib.dates import DateFormatter
import seaborn as sns
sns.set()

In [2]:
path = "/Users/iomacbookair2/Documents/lab/DEIM2023/tweet_csv/trad/220125_trad.csv"
df = pd.read_csv((path))
df['created_at'] = pd.to_datetime(df['created_at'])
df.sort_values(by = 'created_at', ascending = True, inplace = True)
df = df.reset_index(drop=True)
df

,created_at,text,author_id,username,like_count,retweet_count
0,2022-01-25 15:00:06,#THETRAD,1199252360091930625,custom__77,2,0
1,2022-01-25 15:00:13,#THETRAD,965974369343164421,moushachou,1,0
2,2022-01-25 15:00:20,今までの吾郎さんのエピソードを聞いていても人に対して怒るとかないものね。イラチって言うけどそ...,105929459,yuinago,18,6
3,2022-01-25 15:00:21,始まりました♪ ＃THETRAD ＃TOKYOFM ＃稲垣吾郎 ＃吉田明世,106008202,just_56,2,0
4,2022-01-25 15:00:40,#THETRAD 本日もOpenの時間ー♪☺️ #tokyofm #稲垣吾郎 #吉田明世,265231769,masaruhiro18,1,0
...,...,...,...,...,...,...
1199,2022-01-25 16:54:24,今日も楽しかった♪ 芸能界でも感染者が増えてますね💧 吾郎店長も体調管理に 気をつけてくださ...,898881672480931842,akiko3103,5,0
1200,2022-01-25 16:54:33,今日も楽しかったです ツンデレの吾郎店長も♡*° 吾郎店長と吉田さんは また来週ね さよなら...,707705772549873664,DwHaru,1,0
1201,2022-01-25 16:54:38,終わった。 さよならの声優しかった💞 お疲れ様でした。 #THETRAD #稲垣吾郎,1443779933042479112,oleEZwvaVRAPH58,1,0
1202,2022-01-25 16:54:48,今日も楽しかったです｡ 吾郎店長と吉田店員さん､また来週｡ #THETRAD #稲垣吾郎 ...,915421858958159872,makomintia,3,0
1203,2022-01-25 16:54:50,今からタイムフリーでTRAD聴きます😊 #THETRAD #稲垣吾郎 #吉田明世,387668604,nako567,1,0

In [3]:
c_df = df.set_index('created_at').resample('T').count()
like_count_per_minute = df.set_index('created_at')['like_count'].resample('T').sum()
cnt = pd.DataFrame(
    {'created_at' : c_df.index.strftime('%Y-%m-%d %H:%M:%S'), 'tweet' : c_df['text'].values, 'like':like_count_per_minute.values})
cnt

              created_at  tweet  like
0    2022-01-25 15:00:00      6    28
1    2022-01-25 15:01:00      9    18
2    2022-01-25 15:02:00     17    19
3    2022-01-25 15:03:00     24    42
4    2022-01-25 15:04:00     22    73
..                   ...    ...   ...
110  2022-01-25 16:50:00     11  2613
111  2022-01-25 16:51:00     12    25
112  2022-01-25 16:52:00     12    86
113  2022-01-25 16:53:00      6    75
114  2022-01-25 16:54:00      6    11

[115 rows x 3 columns]

In [4]:
filename =  "count.csv"
cnt.to_csv(filename, encoding = 'utf-8-sig')