In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import datetime as dt
from datetime import datetime as dtdt
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import ticker
import matplotlib.dates as mdates
from matplotlib.dates import date2num
from matplotlib.dates import DateFormatter
import seaborn as sns
sns.set()

In [2]:
path = "/Users/iomacbookair2/Documents/lab/DEIM2023/tweet_csv/trad/220124_trad.csv"
df = pd.read_csv((path))
df['created_at'] = pd.to_datetime(df['created_at'])
df.sort_values(by = 'created_at', ascending = True, inplace = True)
df = df.reset_index(drop=True)
df

,created_at,text,author_id,username,like_count,retweet_count
0,2022-01-24 15:00:00,#THETRAD,1376017426920267776,nogiotaradio,4,0
1,2022-01-24 15:00:01,#THETRAD,1183985487901425664,senpuuki_tantan,4,0
2,2022-01-24 15:00:01,１５時！ #tokyofm #THETRAD,1296804548023992329,__Kanday,5,0
3,2022-01-24 15:00:01,#THETRAD,1065212718146236416,Dosankoradio1,4,0
4,2022-01-24 15:00:01,#THETRAD,1173882803777236992,sonana_nogi,3,0
...,...,...,...,...,...,...
2012,2022-01-24 16:53:31,あー、吾郎さんの ラジオジャックの1日が 終わった〜❣️ まだまだ足りない〜😝 けど… ま、...,154074992,goromichiyo,20,1
2013,2022-01-24 16:53:59,吾郎さんのスペシャルラジオデー終わった。 楽しかった。それぞれ少しずつ違う吾郎さんを楽しめま...,106312714,pinot96,159,16
2014,2022-01-24 16:54:40,吾郎店長、午前も午後もラジオ番組の 生出演お疲れ様でした。 楽しかったです♪また明日〜。 ...,911256434108645376,Poodle56Toy,4,0
2015,2022-01-24 16:54:40,この時間は家族の邪魔が入ってすんなり聴けない😂 ミポリンのC、懐かしい〜！ 毎度お騒がせも...,995145044175736832,miyanon105,6,0
2016,2022-01-24 16:54:45,#THETRAD 黒沢さん楽しかったー♪ 今日は ハシゴで生出演 お疲れさまでした💗 ...,97843251,nao_04515,0,0

In [3]:
c_df = df.set_index('created_at').resample('T').count()
like_count_per_minute = df.set_index('created_at')['like_count'].resample('T').sum()
cnt = pd.DataFrame(
    {'created_at' : c_df.index.strftime('%Y-%m-%d %H:%M:%S'), 'tweet' : c_df['text'].values, 'like':like_count_per_minute.values})
cnt

              created_at  tweet  like
0    2022-01-24 15:00:00     29   109
1    2022-01-24 15:01:00     15    37
2    2022-01-24 15:02:00     53   113
3    2022-01-24 15:03:00     57   340
4    2022-01-24 15:04:00     90   166
..                   ...    ...   ...
110  2022-01-24 16:50:00     10    36
111  2022-01-24 16:51:00     18    80
112  2022-01-24 16:52:00     18   145
113  2022-01-24 16:53:00      5   229
114  2022-01-24 16:54:00      3    10

[115 rows x 3 columns]

In [4]:
filename =  "count.csv"
cnt.to_csv(filename, encoding = 'utf-8-sig')